# Generated by Django 2.2.5 on 2019-09-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
